#Esegue build e test su ogni push o PR verso main:
name: CI

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

permissions:
  contents: read

env:
  GO_VERSION: "1.24.4"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Build with Makefile
        run: make build