name: RELEASE

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

permissions:
  contents: write

env:
  GO_VERSION: "1.24.4"

jobs:
  tag-and-release:
    if: >
      ${{
        github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.head.ref, 'release/v')
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main (post-merge)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Compute VERSION from head branch
        run: |
          VERSION="${{ github.event.workflow_run.head_branch }}"
          VERSION="${VERSION#release/v}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Extracted VERSION=$VERSION"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Build with Makefile
        run: make build
        env:
          VERSION: ${{ env.VERSION }}
      - name: Create Git Tag
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${VERSION}" || true
          git push origin "v${VERSION}" || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            🎉 Release v${{ env.VERSION }}
            - Generated from branch `${{ github.event.workflow_run.head_branch }}`
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}